# Constants that are shared throughout the program to avoid typographical errors

BODY = "Body"
COMPLETED_LOCATION = "completed"
CONTENTS = "Contents"
CREATE = "create"
DELETE = "delete"
DESCRIPTION = "description"
DIST_BUCKET = "usu-cs5260-homework-assignment-two-dist"
DYNAMO_DB = "DYNAMO_DB"
ERROR_LOCATION = "error"
LABEL = "label"
LOCAL_DISK = "LOCAL_DISK"
KEY = "Key"
KEY_COUNT = "KeyCount"
OWNER = "owner"
OTHER_ATTRIBUTES = "otherAttributes"
PROCESSING_LOCATION = "processing"
RETRY_PROCESSING_COUNT = 3
REQUEST_BUCKET = "usu-cs5260-homework-assignment-two-requests"
S3 = "S3"
S3_MAX_KEYS_TO_LIST = 10
TYPE = "type"
UPDATE = "update"
UTF8 = "utf-8"
WEB_BUCKET = "usu-cs5260-homework-assignment-two-web"
WIDGET_ID = "widgetId"
